#!/bin/sh
set -eu

mariadb \
  --protocol=socket \
  -uroot \
  -p"${MYSQL_ROOT_PASSWORD}" <<SQL
CREATE USER IF NOT EXISTS
  '${MYSQL_READONLY_USER}'@'%'
  IDENTIFIED BY '${MYSQL_READONLY_PASSWORD}';

ALTER USER
  '${MYSQL_READONLY_USER}'@'%'
  IDENTIFIED BY '${MYSQL_READONLY_PASSWORD}';

GRANT SELECT, SHOW VIEW
  ON \`${MYSQL_DATABASE}\`.*
  TO '${MYSQL_READONLY_USER}'@'%';

FLUSH PRIVILEGES;
SQL